# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_auto_20160910_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expresult',
            name='author',
        ),
        migrations.RemoveField(
            model_name='expresult',
            name='created_date',
        ),
    ]
